import sanitizeHtml from 'sanitize-html';

const problemHtmlOptions: sanitizeHtml.IOptions = {
    allowedTags: [
        'a',
        'abbr',
        'b',
        'blockquote',
        'br',
        'caption',
        'code',
        'dd',
        'del',
        'details',
        'div',
        'dl',
        'dt',
        'em',
        'figcaption',
        'figure',
        'h1',
        'h2',
        'h3',
        'h4',
        'h5',
        'h6',
        'hr',
        'i',
        'img',
        'ins',
        'kbd',
        'li',
        'mark',
        'math',
        'mfrac',
        'mi',
        'mn',
        'mo',
        'mrow',
        'ms',
        'msqrt',
        'msub',
        'msubsup',
        'msup',
        'mtable',
        'mtd',
        'mtext',
        'mtr',
        'ol',
        'p',
        'pre',
        'samp',
        'semantics',
        'small',
        'span',
        'strong',
        'sub',
        'summary',
        'sup',
        'table',
        'tbody',
        'td',
        'tfoot',
        'th',
        'thead',
        'tr',
        'u',
        'ul',
        'var',
    ],
    allowedAttributes: {
        a: ['aria-label', 'href', 'title'],
        img: ['alt', 'height', 'src', 'title', 'width'],
        ol: ['start', 'type'],
        td: ['colspan', 'rowspan'],
        th: ['colspan', 'rowspan', 'scope'],
        math: ['display'],
        mtd: ['columnspan', 'rowspan'],
    },
    allowedSchemes: ['http', 'https', 'mailto'],
    allowedSchemesByTag: {
        img: ['http', 'https'],
    },
    allowedSchemesAppliedToAttributes: ['href', 'src'],
    allowProtocolRelative: false,
    disallowedTagsMode: 'discard',
    exclusiveFilter(frame) {
        if (frame.tag !== 'img') return false;

        const src = frame.attribs.src;
        return !src || !/^https?:\/\//i.test(src);
    },
    nestingLimit: 50,
    nonTextTags: ['script', 'style', 'textarea', 'option', 'iframe', 'object', 'embed', 'svg'],
    parseStyleAttributes: false,
};

export function sanitizeProblemHtml(input: string): string {
    return sanitizeHtml(input, problemHtmlOptions);
}
